---
- name: Ensure users are present
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | join(',') }}"
    append: yes
    state: present
  loop: "{{ iam_users }}"
  tags: [iam, users]

- name: Add SSH keys for users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  when: item.ssh_key is defined
  loop: "{{ iam_users }}"
  tags: [iam, ssh]