---
- name: Ensure required variables are set
  assert:
    that:
      - rust_version is defined
      - rust_version | length > 0
    fail_msg: "You must define rust_version to use this role."
  tags: [rust, prereq]

- name: "Check if {{ solana_user }} user exists"
  ansible.builtin.getent:
    database: passwd
    key: "{{ solana_user }}"
  register: sol_user_check
  tags: [precheck]

- name: "Fail if {{ solana_user }} user is not found"
  ansible.builtin.fail:
    msg: >
      "The user {{solana_user}} is required but was not found on this host.
      Please create the user manually or ensure it's provisioned by a prior role."
  when: solana_user not in sol_user_check.ansible_facts.getent_passwd
  tags: [precheck]
