---
- name: Verify Solana CLI installation
  block:
    - name: Verify - Refresh shell environment and verify PATH
      ansible.builtin.shell: |
        . "$HOME/.bashrc"
        echo $PATH
      register: shell_env_path
      changed_when: false
      tags: [solana_cli, verify]

    - name: Verify - Show current PATH
      debug:
        msg: "PATH after sourcing: {{ shell_env_path.stdout }}"

    - name: Verify - Check if solana CLI is available
      ansible.builtin.shell: |
        solana --version
      environment:
        PATH: "{{ shell_env_path.stdout }}"
      register: solana_cli_version
      changed_when: false
      failed_when: solana_cli_version.rc != 0
      tags: [solana_cli, verify]

    - name: Verify - Print solana CLI version
      debug:
        msg: "Solana CLI is installed: {{ solana_cli_version.stdout }}"

    - name: Verify - Run 'solana config get' to validate config access
      ansible.builtin.shell: |
        solana config get
      environment:
        PATH: "{{ shell_env_path.stdout }}"
      register: solana_config_output
      changed_when: false
      failed_when: solana_config_output.rc != 0
      tags: [solana_cli, verify]

    - name: Show current Solana CLI config
      debug:
        msg: "{{ solana_config_output.stdout_lines }}"
